// Code generated by protoc-gen-go. DO NOT EDIT.
// source: openprio_pt_position_data.proto

package openprio_pt_position_data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// This enum describes the status of the (unlocking of the) doors of the vehicle.
// DoorOpenStatus is OPEN when the doors are open. When the doors are locked the status is CLOSED. The DoorOpenStatus is RELEASED  when the passengers can open the doors but de the doors are physically closed.
type DoorOpeningStatus int32

const (
	DoorOpeningStatus_DOOR_OPENING_STATUS_CLOSED   DoorOpeningStatus = 0
	DoorOpeningStatus_DOOR_OPENING_STATUS_OPEN     DoorOpeningStatus = 1
	DoorOpeningStatus_DOOR_OPENING_STATUS_NO_DATA  DoorOpeningStatus = 2
	DoorOpeningStatus_DOOR_OPENING_STATUS_RELEASED DoorOpeningStatus = 3
)

var DoorOpeningStatus_name = map[int32]string{
	0: "DOOR_OPENING_STATUS_CLOSED",
	1: "DOOR_OPENING_STATUS_OPEN",
	2: "DOOR_OPENING_STATUS_NO_DATA",
	3: "DOOR_OPENING_STATUS_RELEASED",
}

var DoorOpeningStatus_value = map[string]int32{
	"DOOR_OPENING_STATUS_CLOSED":   0,
	"DOOR_OPENING_STATUS_OPEN":     1,
	"DOOR_OPENING_STATUS_NO_DATA":  2,
	"DOOR_OPENING_STATUS_RELEASED": 3,
}

func (x DoorOpeningStatus) String() string {
	return proto.EnumName(DoorOpeningStatus_name, int32(x))
}

func (DoorOpeningStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_91db169fa4ecc494, []int{0}
}

// This enum describes if the stop button is activated
// indicating that passengers want tot get out at it's next stop
type StopButtonStatus int32

const (
	StopButtonStatus_STOP_BUTTON_STATUS_NOT_ACTIVATED StopButtonStatus = 0
	StopButtonStatus_STOP_BUTTON_STATUS_ACTIVATED     StopButtonStatus = 1
	StopButtonStatus_STOP_BUTTON_STATUS_NO_DATA       StopButtonStatus = 2
)

var StopButtonStatus_name = map[int32]string{
	0: "STOP_BUTTON_STATUS_NOT_ACTIVATED",
	1: "STOP_BUTTON_STATUS_ACTIVATED",
	2: "STOP_BUTTON_STATUS_NO_DATA",
}

var StopButtonStatus_value = map[string]int32{
	"STOP_BUTTON_STATUS_NOT_ACTIVATED": 0,
	"STOP_BUTTON_STATUS_ACTIVATED":     1,
	"STOP_BUTTON_STATUS_NO_DATA":       2,
}

func (x StopButtonStatus) String() string {
	return proto.EnumName(StopButtonStatus_name, int32(x))
}

func (StopButtonStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_91db169fa4ecc494, []int{1}
}

// Message that vehicle sends every second.
type LocationMessage struct {
	VehicleDescriptor    *VehicleDescriptor `protobuf:"bytes,1,opt,name=vehicle_descriptor,json=vehicleDescriptor,proto3" json:"vehicle_descriptor,omitempty"`
	Position             *Position          `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Timestamp            int64              `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DoorStatus           DoorOpeningStatus  `protobuf:"varint,4,opt,name=door_status,json=doorStatus,proto3,enum=DoorOpeningStatus" json:"door_status,omitempty"`
	StopButtonStatus     StopButtonStatus   `protobuf:"varint,5,opt,name=stop_button_status,json=stopButtonStatus,proto3,enum=StopButtonStatus" json:"stop_button_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LocationMessage) Reset()         { *m = LocationMessage{} }
func (m *LocationMessage) String() string { return proto.CompactTextString(m) }
func (*LocationMessage) ProtoMessage()    {}
func (*LocationMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_91db169fa4ecc494, []int{0}
}

func (m *LocationMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationMessage.Unmarshal(m, b)
}
func (m *LocationMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationMessage.Marshal(b, m, deterministic)
}
func (m *LocationMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationMessage.Merge(m, src)
}
func (m *LocationMessage) XXX_Size() int {
	return xxx_messageInfo_LocationMessage.Size(m)
}
func (m *LocationMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LocationMessage proto.InternalMessageInfo

func (m *LocationMessage) GetVehicleDescriptor() *VehicleDescriptor {
	if m != nil {
		return m.VehicleDescriptor
	}
	return nil
}

func (m *LocationMessage) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *LocationMessage) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *LocationMessage) GetDoorStatus() DoorOpeningStatus {
	if m != nil {
		return m.DoorStatus
	}
	return DoorOpeningStatus_DOOR_OPENING_STATUS_CLOSED
}

func (m *LocationMessage) GetStopButtonStatus() StopButtonStatus {
	if m != nil {
		return m.StopButtonStatus
	}
	return StopButtonStatus_STOP_BUTTON_STATUS_NOT_ACTIVATED
}

type Position struct {
	Latitude  float32 `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float32 `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy  float32 `protobuf:"fixed32,3,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Speed     float32 `protobuf:"fixed32,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Bearing   float32 `protobuf:"fixed32,5,opt,name=bearing,proto3" json:"bearing,omitempty"`
	// the odometer is always used relatively,
	// the odometer may be either the total distance a vehicle has traveled during its lifetime,
	// today or during the current trip (resetting more often is not allowed)
	Odometer             int64    `protobuf:"varint,6,opt,name=odometer,proto3" json:"odometer,omitempty"`
	Hdop                 float32  `protobuf:"fixed32,7,opt,name=hdop,proto3" json:"hdop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_91db169fa4ecc494, []int{1}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Position) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Position) GetAccuracy() float32 {
	if m != nil {
		return m.Accuracy
	}
	return 0
}

func (m *Position) GetSpeed() float32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Position) GetBearing() float32 {
	if m != nil {
		return m.Bearing
	}
	return 0
}

func (m *Position) GetOdometer() int64 {
	if m != nil {
		return m.Odometer
	}
	return 0
}

func (m *Position) GetHdop() float32 {
	if m != nil {
		return m.Hdop
	}
	return 0
}

// Fields to identify vehicle
type VehicleDescriptor struct {
	DataOwnerCode string `protobuf:"bytes,1,opt,name=data_owner_code,json=dataOwnerCode,proto3" json:"data_owner_code,omitempty"`
	// One of block_code and vehicle_number is required
	BlockCode            int32    `protobuf:"varint,2,opt,name=block_code,json=blockCode,proto3" json:"block_code,omitempty"`
	VehicleNumber        int32    `protobuf:"varint,3,opt,name=vehicle_number,json=vehicleNumber,proto3" json:"vehicle_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VehicleDescriptor) Reset()         { *m = VehicleDescriptor{} }
func (m *VehicleDescriptor) String() string { return proto.CompactTextString(m) }
func (*VehicleDescriptor) ProtoMessage()    {}
func (*VehicleDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_91db169fa4ecc494, []int{2}
}

func (m *VehicleDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VehicleDescriptor.Unmarshal(m, b)
}
func (m *VehicleDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VehicleDescriptor.Marshal(b, m, deterministic)
}
func (m *VehicleDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VehicleDescriptor.Merge(m, src)
}
func (m *VehicleDescriptor) XXX_Size() int {
	return xxx_messageInfo_VehicleDescriptor.Size(m)
}
func (m *VehicleDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_VehicleDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_VehicleDescriptor proto.InternalMessageInfo

func (m *VehicleDescriptor) GetDataOwnerCode() string {
	if m != nil {
		return m.DataOwnerCode
	}
	return ""
}

func (m *VehicleDescriptor) GetBlockCode() int32 {
	if m != nil {
		return m.BlockCode
	}
	return 0
}

func (m *VehicleDescriptor) GetVehicleNumber() int32 {
	if m != nil {
		return m.VehicleNumber
	}
	return 0
}

func init() {
	proto.RegisterEnum("DoorOpeningStatus", DoorOpeningStatus_name, DoorOpeningStatus_value)
	proto.RegisterEnum("StopButtonStatus", StopButtonStatus_name, StopButtonStatus_value)
	proto.RegisterType((*LocationMessage)(nil), "LocationMessage")
	proto.RegisterType((*Position)(nil), "Position")
	proto.RegisterType((*VehicleDescriptor)(nil), "VehicleDescriptor")
}

func init() { proto.RegisterFile("openprio_pt_position_data.proto", fileDescriptor_91db169fa4ecc494) }

var fileDescriptor_91db169fa4ecc494 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x4d, 0x6f, 0xda, 0x40,
	0x10, 0xad, 0x4d, 0x48, 0x60, 0xa2, 0x24, 0x30, 0xea, 0xc1, 0x4a, 0x69, 0x63, 0xa1, 0xa6, 0x42,
	0x39, 0x70, 0x48, 0x7e, 0x40, 0xe5, 0x00, 0xaa, 0x22, 0x51, 0x8c, 0xd6, 0x4e, 0xae, 0x2b, 0x63,
	0xaf, 0x88, 0x55, 0xf0, 0xac, 0xd6, 0x4b, 0xaa, 0xf6, 0xd6, 0x5f, 0xd0, 0x4b, 0x7f, 0x50, 0x7f,
	0x5a, 0xb4, 0xcb, 0x97, 0x44, 0x7c, 0xf3, 0x7b, 0x6f, 0xde, 0xec, 0xbc, 0x9d, 0x35, 0x5c, 0x91,
	0x14, 0x85, 0x54, 0x39, 0x71, 0xa9, 0xb9, 0xa4, 0x32, 0xd7, 0x39, 0x15, 0x3c, 0x4b, 0x74, 0xd2,
	0x97, 0x8a, 0x34, 0x75, 0xff, 0xba, 0x70, 0x31, 0xa6, 0x34, 0x31, 0xfc, 0x77, 0x51, 0x96, 0xc9,
	0x5c, 0x60, 0x00, 0xf8, 0x22, 0x9e, 0xf3, 0x74, 0x21, 0x78, 0x26, 0xca, 0x54, 0xe5, 0x52, 0x93,
	0xf2, 0x1c, 0xdf, 0xe9, 0x9d, 0xde, 0x62, 0xff, 0x69, 0x2d, 0x0d, 0x77, 0x0a, 0x6b, 0xbf, 0x1c,
	0x52, 0x78, 0x0d, 0x8d, 0xed, 0x69, 0x9e, 0x6b, 0x8d, 0xcd, 0xfe, 0x74, 0x43, 0xb0, 0x9d, 0x84,
	0x1d, 0x68, 0xea, 0x7c, 0x29, 0x4a, 0x9d, 0x2c, 0xa5, 0x57, 0xf3, 0x9d, 0x5e, 0x8d, 0xed, 0x09,
	0xbc, 0x83, 0xd3, 0x8c, 0x48, 0xf1, 0x52, 0x27, 0x7a, 0x55, 0x7a, 0x47, 0xbe, 0xd3, 0x3b, 0xbf,
	0xc5, 0xfe, 0x90, 0x48, 0x85, 0x52, 0x14, 0x79, 0x31, 0x8f, 0xac, 0xc2, 0xc0, 0x94, 0xad, 0xbf,
	0xf1, 0x2b, 0x60, 0xa9, 0x49, 0xf2, 0xd9, 0x4a, 0x6b, 0x2a, 0xb6, 0xde, 0xba, 0xf5, 0xb6, 0xfb,
	0x91, 0x26, 0x79, 0x6f, 0x95, 0x8d, 0xb5, 0x55, 0x1e, 0x30, 0xdd, 0xff, 0x0e, 0x34, 0xb6, 0xa3,
	0xe2, 0x25, 0x34, 0x16, 0x89, 0xce, 0xf5, 0x2a, 0x13, 0xf6, 0x02, 0x5c, 0xb6, 0xc3, 0x66, 0xf8,
	0x05, 0x15, 0xf3, 0xb5, 0xe8, 0x5a, 0x71, 0x4f, 0x18, 0x67, 0x92, 0xa6, 0x2b, 0x95, 0xa4, 0xbf,
	0x6c, 0x32, 0x97, 0xed, 0x30, 0xbe, 0x87, 0x7a, 0x29, 0x85, 0xc8, 0x6c, 0x24, 0x97, 0xad, 0x01,
	0x7a, 0x70, 0x32, 0x13, 0x89, 0xca, 0x8b, 0xb9, 0x1d, 0xd7, 0x65, 0x5b, 0x68, 0x7a, 0x51, 0x46,
	0x4b, 0xa1, 0x85, 0xf2, 0x8e, 0xed, 0x2d, 0xed, 0x30, 0x22, 0x1c, 0x3d, 0x67, 0x24, 0xbd, 0x13,
	0x6b, 0xb1, 0xdf, 0xdd, 0x3f, 0x0e, 0xb4, 0xdf, 0xac, 0x09, 0xbf, 0xc0, 0x85, 0x59, 0x3c, 0xa7,
	0x9f, 0x85, 0x50, 0x3c, 0xa5, 0x4d, 0xa4, 0x26, 0x3b, 0x33, 0x74, 0x68, 0xd8, 0x01, 0x65, 0x02,
	0x3f, 0x02, 0xcc, 0x16, 0x94, 0xfe, 0x58, 0x97, 0x98, 0x60, 0x75, 0xd6, 0xb4, 0x8c, 0x95, 0xaf,
	0xe1, 0x7c, 0xfb, 0x3a, 0x8a, 0xd5, 0x72, 0x26, 0x94, 0x8d, 0x57, 0x67, 0x67, 0x1b, 0x76, 0x62,
	0xc9, 0x9b, 0x7f, 0x0e, 0xb4, 0xdf, 0x6c, 0x0a, 0x3f, 0xc1, 0xe5, 0x30, 0x0c, 0x19, 0x0f, 0xa7,
	0xa3, 0xc9, 0xc3, 0xe4, 0x1b, 0x8f, 0xe2, 0x20, 0x7e, 0x8c, 0xf8, 0x60, 0x1c, 0x46, 0xa3, 0x61,
	0xeb, 0x1d, 0x76, 0xc0, 0xab, 0xd2, 0x0d, 0x6c, 0x39, 0x78, 0x05, 0x1f, 0xaa, 0xd4, 0x49, 0xc8,
	0x87, 0x41, 0x1c, 0xb4, 0x5c, 0xf4, 0xa1, 0x53, 0x55, 0xc0, 0x46, 0xe3, 0x51, 0x60, 0x0e, 0xa8,
	0xdd, 0xfc, 0x86, 0xd6, 0xe1, 0x1b, 0xc0, 0xcf, 0xe0, 0x47, 0x71, 0x38, 0xe5, 0xf7, 0x8f, 0x71,
	0x1c, 0x4e, 0xf6, 0x5d, 0x63, 0x1e, 0x0c, 0xe2, 0x87, 0xa7, 0x20, 0xb6, 0xa3, 0xf9, 0xd0, 0xa9,
	0xa8, 0xda, 0x57, 0x38, 0x26, 0x5c, 0x65, 0x9f, 0xcd, 0x74, 0xb3, 0x63, 0xfb, 0xcb, 0xdd, 0xbd,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x04, 0xa7, 0x03, 0x95, 0x03, 0x00, 0x00,
}
